name: pkar_sla_wedding_app
description: "A wedding application with Khmer language support."

# Prevent accidental publishing
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Khmer OS Battambang
      fonts:
        - asset: fonts/KhmerOSBattambang-Regular.ttf
          weight: 700
    - family: Noto Sans Khmer
      fonts:
        - asset: fonts/NotoSansKhmer.ttf
