name: pkar_sla_wedding_app
description: "A wedding application with Khmer language support."

# Prevent accidental publishing
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#9BFA9B"
  image: "assets/splash/app_splash.png"
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Khmer OS Battambang
      fonts:
        - asset: fonts/KhmerOSBattambang-Regular.ttf
          weight: 700
    - family: Noto Sans Khmer
      fonts:
        - asset: fonts/NotoSansKhmer.ttf
